---
javascripts:
- base:
  - jquery-1.4.2.min
  - json2.min
  - jquery.textarea
  - modernizr-1.1.min
  - jquery.placeholder.min
  - progressive_enhancement
  - application
stylesheets:
- base:
  - reset
  - styles
